apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
      app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "koneyayangolo/frontback-tp-sca:yko-backend-v2"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "200Mi"
              cpu: "700m"
          readinessProbe:
            tcpSocket:
              port: 9991
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9991
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: server.port
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: port
          ports:
          - containerPort: 9991